= Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables,
either per role or per role group, where the more specific override (role group) has precedence over
the less specific one (role).

IMPORTANT: Overriding certain properties which are set by the operator (such as the `STATS_LOGGER`)
can interfere with the operator and can lead to problems.

== Configuration Properties

For a role or role group, at the same level of `config`, you can specify `configOverrides` for the
`superset_config.py`. For example, if you want to set the CSV export encoding and the preferred
databases adapt the `nodes` section of the cluster resource as follows:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config: {}
      configOverrides:
        superset_config.py:
          CSV_EXPORT: "{'encoding': 'utf-8'}"
          PREFERRED_DATABASES: |-
            [
                'PostgreSQL',
                'Presto',
                'MySQL',
                'SQLite',
                # etc.
            ]
----

Just as for the `config`, it is possible to specify this at the role level as well:

[source,yaml]
----
nodes:
  configOverrides:
    superset_config.py:
      CSV_EXPORT: "{'encoding': 'utf-8'}"
      PREFERRED_DATABASES: |-
        [
            'PostgreSQL',
            'Presto',
            'MySQL',
            'SQLite',
            # etc.
        ]
  roleGroups:
    default:
      config: {}
----

All override property values must be strings. They are treated as Python expressions. So care must
be taken to not produce an invalid configuration.

For a full list of configuration options we refer to the
https://github.com/apache/superset/blob/master/superset/config.py[main config file for Superset].

== Environment Variables

In a similar fashion, environment variables can be (over)written. For example per role group:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config: {}
      envOverrides:
        FLASK_ENV: development
----

or per role:

[source,yaml]
----
nodes:
  envOverrides:
    FLASK_ENV: development
  roleGroups:
    default:
      config: {}
----

// cliOverrides don't make sense for this operator, so the feature is omitted for now
