---
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units: []
    properties:
      - property: &credentialsSecret
          propertyNames:
            - name: "credentialsSecret"
              kind:
                type: "env"
          datatype:
            type: "string"
          roles:
            - name: "node"
              required: true
          asOfVersion: "0.0.0"
          description: "The secret where the Superset credentials are stored."
kind: ConfigMap
metadata:
  name: superset-operator-configmap
  labels:
    app.kubernetes.io/name: superset-operator
    app.kubernetes.io/instance: superset-operator
    app.kubernetes.io/version: "0.4.0"
