# =============
# This file is automatically generated from the templates in stackabletech/operator-templating
# DON'T MANUALLY EDIT THIS FILE
# =============

.PHONY: docker chart-lint compile-chart

TAG    := $(shell git rev-parse --short HEAD)

VERSION := $(shell cargo metadata --format-version 1 | jq '.packages[] | select(.name=="stackable-superset-operator") | .version')

docker:
	docker build --force-rm -t "docker.stackable.tech/stackable/superset-operator:${VERSION}" -t "docker.stackable.tech/stackable/superset-operator:latest" -f docker/Dockerfile .
	echo "${NEXUS_PASSWORD}" | docker login --username github --password-stdin docker.stackable.tech
	docker push --all-tags docker.stackable.tech/stackable/superset-operator

## Chart related targets
compile-chart: version crds config 

chart-clean:
	rm -rf deploy/helm/superset-operator/configs
	rm -rf deploy/helm/superset-operator/templates/crds.yaml

version:
	yq eval -i '.version = ${VERSION} | .appVersion = ${VERSION}' deploy/helm/superset-operator/Chart.yaml


config: deploy/helm/superset-operator/configs

deploy/helm/superset-operator/configs:
	cp -r deploy/config-spec deploy/helm/superset-operator/configs

crds: deploy/helm/superset-operator/crds/crds.yaml

deploy/helm/superset-operator/crds/crds.yaml:
	mkdir -p deploy/helm/superset-operator/crds
	cat deploy/crd/*.yaml | yq e '.metadata.annotations["helm.sh/resource-policy"]="keep"' - > ${@}

chart-lint: compile-chart
	docker run -it -v $(shell pwd):/build/helm-charts -w /build/helm-charts quay.io/helmpack/chart-testing:v3.4.0  ct lint --config deploy/helm/chart_testing.yaml
