apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  version: 1.3.2
  nodes:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-superset-credentials
