---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
spec:
  version: 1.5.1-stackable0.1.0
  statsdExporterVersion: v0.22.4
  credentialsSecret: simple-superset-credentials
  loadExamplesOnInit: true
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
