= Stackable Operator for Apache Superset
:description: The Stackable operator for Apache Superset is a Kubernetes operator that can manage Apache Superset clusters. Learn about its features, resources, dependencies and demos, and see the list of supported Superset versions.
:keywords: Stackable operator, Apache Superset, Kubernetes, operator, data science, data exploration
:superset: https://superset.apache.org/
:crs: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

The Stackable operator for {superset}[Apache Superset] is an operator that can deploy and manage Apache Superset clusters on Kubernetes.
Superset is a data exploration and visualization tool that connects to data sources via SQL.
Store your data in Apache Druid or Trino, and manage your Druid and Trino instances with the Stackable operators for xref:druid:index.adoc[Apache Druid] or xref:trino:index.adoc[Trino].
This operator helps you manage your Superset instances on Kubernetes efficiently.

== Getting started

Get started using Superset with Stackable operator by following the xref:getting_started/index.adoc[].
It guides you through installing the operator alongside a PostgreSQL database, connecting to your Superset instance and analyzing some preloaded example data.

== Resources

The operator manages two {crs}[custom resources]: The _SupersetCluster_ and _DruidConnection_.
It creates a number of different Kubernetes resources based on the custom resources.

=== Custom resources

The SupersetCluster is the main resource for the configuration of the Superset instance.
The resource defines only one xref:concepts:roles-and-role-groups.adoc[role], the `node`.
The various configuration options are explained in the xref:usage-guide/index.adoc[].
It helps you tune your cluster to your needs by configuring xref:usage-guide/storage-resource-configuration.adoc[resource usage], xref:usage-guide/security.adoc[security], xref:usage-guide/logging.adoc[logging] and more.

DruidConnection resources link a Superset and Druid instance.
It lets you define this connection in the familiar way of deploying a resource (instead of configuring the connection via the Superset UI or API).
The operator configures the connection between Druid and the Superset instance.

=== Kubernetes resources

Based on the custom resources you define, the operator creates ConfigMaps, StatefulSets and Services.

image::superset_overview.drawio.svg[A diagram depicting the Kubernetes resources created by the operator]

The diagram above depicts all the Kubernetes resources created by the operator, and how they relate to each other.
The Job created for the DruidConnnection resource is not shown.

For every xref:concepts:roles-and-role-groups.adoc#_role_groups[role group] you define, the operator creates a StatefulSet with the amount of replicas defined in the RoleGroup.
Every Pod in the StatefulSet has two containers: the main container running Superset and a sidecar container gathering metrics for xref:operators:monitoring.adoc[].
The operator creates a Service for the `node` role as well as a single service per role group.

Additionally, a ConfigMap is created for each RoleGroup.
These ConfigMaps contains two files: `log_config.py` and `superset_config.py` which contain logging and general Superset configuration respectively.

== Required external component: Metastore SQL database

Superset requires an SQL database in which to store its metadata, dashboards and users.
The xref:getting_started/index.adoc[] guides you through installing an example database with a Superset instance that you can use to get started, but is not suitable for production use.
Follow the setup instructions for one of the xref:required-external-components.adoc[supported databases] for a production database.

== Connecting to data sources

Superset does not store its own data, instead it connects to other products where data is stored.
On the Stackable Platform the two commonly used choices are xref:druid:index.adoc[Apache Druid] and xref:trino:index.adoc[Trino].
For Druid there is a way to xref:usage-guide/connecting-druid.adoc[connect a Druid instance declaratively] with a custom resource.
For Trino this is on the roadmap.
Have a look at the demos linked <<demos, below>> for examples of using Superset with Druid or Trino.

== [[demos]]Demos

Many of the Stackable xref:demos:index.adoc[demos] use Superset in the stack for data visualization and explaration.
The demos come in two main variants.

=== With Druid

The xref:demos:nifi-kafka-druid-earthquake-data.adoc[] and xref:demos:nifi-kafka-druid-water-level-data.adoc[] demos
show Superset connected to xref:druid:index.adoc[Druid], exploring earthquake and water level data respectively.

=== With Trino

The xref:demos:spark-k8s-anomaly-detection-taxi-data.adoc[], xref:demos:trino-taxi-data.adoc[], xref:demos:trino-iceberg.adoc[] and xref:demos:data-lakehouse-iceberg-trino-spark.adoc[] demos all use a xref:trino:index.adoc[Trino] instance on top of S3 storage that hold data to analyze. Superset is connected to Trino to analyze a variety of different datasets.

== Supported versions

The Stackable operator for Apache Superset currently supports the Superset versions listed below.
To use a specific Superset version in your SupersetCluster, you have to specify an image - this is explained in the xref:concepts:product-image-selection.adoc[] documentation.
The operator also supports running images from a custom registry or running entirely customized images; both of these cases are explained under xref:concepts:product-image-selection.adoc[] as well.

include::partial$supported-versions.adoc[]
