= Installation

On this page you will install the Stackable Superset Operator as well as the commons, secret and listener operator which are required by all Stackable Operators.

== Stackable Operators

There are multiple ways to install the Stackable Operator for Apache Zookeeper.
`stackablectl` is the preferred way but Helm is also supported.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl (recommended)::
+
--
`stackablectl` is the command line tool to interact with Stackable operators and our recommended way to install
Operators. Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed `stackablectl`, run the following command to install all Operators necessary for Superset:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool will show

[source]
include::example$getting_started/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
For example, you can use the `--cluster kind` flag to create a Kubernetes cluster with link:https://kind.sigs.k8s.io/[kind].
--

Helm::
+
--
You can also use Helm to install the Operators.
Add the Stackable Helm repository:
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm will deploy the operators in a Kubernetes Deployment and apply the CRDs for the Superset service (as well as the CRDs for the required operators).
You are now ready to deploy Superset in Kubernetes.
--
====

== What's next

xref:getting_started/first_steps.adoc[Deploy a Superset instance and connect to it].
