---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
spec:
  image:
    productVersion: 2.1.0
    stackableVersion: 0.0.0-dev
  clusterConfig:
    credentialsSecret: simple-superset-credentials
    listenerClass: external-unstable
    loadExamplesOnInit: true
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
