---
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql-credentials
stringData:
  username: superset
  password: superset
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
spec:
  image:
    productVersion: 6.0.0
  clusterConfig:
    credentialsSecretName: superset-admin-credentials
    metadataDatabase:
      postgresql:
        host: superset-postgresql
        database: superset
        credentialsSecretName: superset-postgresql-credentials
  nodes:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
