---
apiVersion: batch/v1
kind: Job
metadata:
  name: superset-load-examples
spec:
  template:
    spec:
      volumes:
      - configMap:
          defaultMode: 420
          name: simple-superset-node-default
        name: config
      containers:
      - name: superset
        image: oci.stackable.tech/sdp/superset:6.0.0-stackable0.0.0-dev
        command: [
          "/bin/bash",
          "-c",
          "export SQLALCHEMY_DATABASE_URI=\"postgresql://${DB_USERNAME}:${DB_PASSWORD}@superset-postgresql.default.svc.cluster.local/superset\" && \
          mkdir --parents /stackable/app/pythonpath && \
          cp /stackable/config/* /stackable/app/pythonpath && \
          echo 'SQLALCHEMY_EXAMPLES_URI = os.environ.get(\"SQLALCHEMY_DATABASE_URI\")' >> /stackable/app/pythonpath/superset_config.py && \
          superset load_examples"
        ]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: simple-superset-secret-key
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: superset-postgresql-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: superset-postgresql-credentials
        volumeMounts:
        - mountPath: /stackable/config
          name: config
        resources:
          limits:
            cpu: 1200m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 1000Mi
      restartPolicy: Never
  backoffLimit: 4
